version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: your_dockerhub_user/fastapi_app:latest
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  postgres_data: