name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Собираем Docker образ
      - name: Build Docker image
        run: docker build -t fastapi-app .

      # 3. Запускаем контейнер
      - name: Run container
        run: |
            docker run -d -p 8001:8001 --name myapp fastapi-app
      
      - name: Show container logs
        run: |
          sleep 5
          docker logs myapp

      - name: Show running containers
        run: docker ps -a

      # 4. Проверяем API
      - name: Wait for API
        run: |
          for i in {1..20}; do
            echo "Attempt $i..."
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8001 || true)

            if [ "$response" = "200" ]; then
              echo "API is up!"
              exit 0
            fi

            echo "Status: $response"
            sleep 2
          done

          echo "API did not start in time"
          docker logs myapp
          exit 1